# Copyright 2020 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build the manager binary
ARG GOVER=1.15
ARG METALCTL_URL
ARG METALCTL_HMAC
ARG MINI_LAB_PATH
ARG IMAGE_TAG
FROM golang:${GOVER} as builder

ENV METALCTL_URL=$METALCTL_URL
ENV METALCTL_HMAC=$METALCTL_HMAC
ENV IMAGE_TAG=$IMAGE_TAG

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy source code(redundantly)
COPY . .

# Set kubeconfig
ENV KUBECONFIG=/workspace/.kubeconfig

# Install kustomize
RUN make kustomize
ENV PATH=$PATH:/workspace/hack/tools/bin/

CMD make e2e