// +build !ignore_autogenerated

/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1alpha4 "github.com/metal-stack/cluster-api-provider-metalstack/api/v1alpha4"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1alpha3 "sigs.k8s.io/cluster-api/api/v1alpha3"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*MetalStackCluster)(nil), (*v1alpha4.MetalStackCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster(a.(*MetalStackCluster), b.(*v1alpha4.MetalStackCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackCluster)(nil), (*MetalStackCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster(a.(*v1alpha4.MetalStackCluster), b.(*MetalStackCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackClusterList)(nil), (*v1alpha4.MetalStackClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackClusterList_To_v1alpha4_MetalStackClusterList(a.(*MetalStackClusterList), b.(*v1alpha4.MetalStackClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackClusterList)(nil), (*MetalStackClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackClusterList_To_v1alpha3_MetalStackClusterList(a.(*v1alpha4.MetalStackClusterList), b.(*MetalStackClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackClusterSpec)(nil), (*v1alpha4.MetalStackClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec(a.(*MetalStackClusterSpec), b.(*v1alpha4.MetalStackClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackClusterSpec)(nil), (*MetalStackClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec(a.(*v1alpha4.MetalStackClusterSpec), b.(*MetalStackClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackClusterStatus)(nil), (*v1alpha4.MetalStackClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus(a.(*MetalStackClusterStatus), b.(*v1alpha4.MetalStackClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackClusterStatus)(nil), (*MetalStackClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus(a.(*v1alpha4.MetalStackClusterStatus), b.(*MetalStackClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackFirewall)(nil), (*v1alpha4.MetalStackFirewall)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackFirewall_To_v1alpha4_MetalStackFirewall(a.(*MetalStackFirewall), b.(*v1alpha4.MetalStackFirewall), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackFirewall)(nil), (*MetalStackFirewall)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackFirewall_To_v1alpha3_MetalStackFirewall(a.(*v1alpha4.MetalStackFirewall), b.(*MetalStackFirewall), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackFirewallList)(nil), (*v1alpha4.MetalStackFirewallList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackFirewallList_To_v1alpha4_MetalStackFirewallList(a.(*MetalStackFirewallList), b.(*v1alpha4.MetalStackFirewallList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackFirewallList)(nil), (*MetalStackFirewallList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackFirewallList_To_v1alpha3_MetalStackFirewallList(a.(*v1alpha4.MetalStackFirewallList), b.(*MetalStackFirewallList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackFirewallSpec)(nil), (*v1alpha4.MetalStackFirewallSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(a.(*MetalStackFirewallSpec), b.(*v1alpha4.MetalStackFirewallSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackFirewallSpec)(nil), (*MetalStackFirewallSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(a.(*v1alpha4.MetalStackFirewallSpec), b.(*MetalStackFirewallSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackFirewallStatus)(nil), (*v1alpha4.MetalStackFirewallStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus(a.(*MetalStackFirewallStatus), b.(*v1alpha4.MetalStackFirewallStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackFirewallStatus)(nil), (*MetalStackFirewallStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus(a.(*v1alpha4.MetalStackFirewallStatus), b.(*MetalStackFirewallStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachine)(nil), (*v1alpha4.MetalStackMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachine_To_v1alpha4_MetalStackMachine(a.(*MetalStackMachine), b.(*v1alpha4.MetalStackMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachine)(nil), (*MetalStackMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachine_To_v1alpha3_MetalStackMachine(a.(*v1alpha4.MetalStackMachine), b.(*MetalStackMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineList)(nil), (*v1alpha4.MetalStackMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineList_To_v1alpha4_MetalStackMachineList(a.(*MetalStackMachineList), b.(*v1alpha4.MetalStackMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineList)(nil), (*MetalStackMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineList_To_v1alpha3_MetalStackMachineList(a.(*v1alpha4.MetalStackMachineList), b.(*MetalStackMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineSpec)(nil), (*v1alpha4.MetalStackMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(a.(*MetalStackMachineSpec), b.(*v1alpha4.MetalStackMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineSpec)(nil), (*MetalStackMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(a.(*v1alpha4.MetalStackMachineSpec), b.(*MetalStackMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineStatus)(nil), (*v1alpha4.MetalStackMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus(a.(*MetalStackMachineStatus), b.(*v1alpha4.MetalStackMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineStatus)(nil), (*MetalStackMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus(a.(*v1alpha4.MetalStackMachineStatus), b.(*MetalStackMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineTemplate)(nil), (*v1alpha4.MetalStackMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineTemplate_To_v1alpha4_MetalStackMachineTemplate(a.(*MetalStackMachineTemplate), b.(*v1alpha4.MetalStackMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineTemplate)(nil), (*MetalStackMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineTemplate_To_v1alpha3_MetalStackMachineTemplate(a.(*v1alpha4.MetalStackMachineTemplate), b.(*MetalStackMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineTemplateList)(nil), (*v1alpha4.MetalStackMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineTemplateList_To_v1alpha4_MetalStackMachineTemplateList(a.(*MetalStackMachineTemplateList), b.(*v1alpha4.MetalStackMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineTemplateList)(nil), (*MetalStackMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineTemplateList_To_v1alpha3_MetalStackMachineTemplateList(a.(*v1alpha4.MetalStackMachineTemplateList), b.(*MetalStackMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineTemplateResource)(nil), (*v1alpha4.MetalStackMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource(a.(*MetalStackMachineTemplateResource), b.(*v1alpha4.MetalStackMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineTemplateResource)(nil), (*MetalStackMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource(a.(*v1alpha4.MetalStackMachineTemplateResource), b.(*MetalStackMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MetalStackMachineTemplateSpec)(nil), (*v1alpha4.MetalStackMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec(a.(*MetalStackMachineTemplateSpec), b.(*v1alpha4.MetalStackMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha4.MetalStackMachineTemplateSpec)(nil), (*MetalStackMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec(a.(*v1alpha4.MetalStackMachineTemplateSpec), b.(*MetalStackMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster(in *MetalStackCluster, out *v1alpha4.MetalStackCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster(in *MetalStackCluster, out *v1alpha4.MetalStackCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster(in, out, s)
}

func autoConvert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster(in *v1alpha4.MetalStackCluster, out *MetalStackCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster(in *v1alpha4.MetalStackCluster, out *MetalStackCluster, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster(in, out, s)
}

func autoConvert_v1alpha3_MetalStackClusterList_To_v1alpha4_MetalStackClusterList(in *MetalStackClusterList, out *v1alpha4.MetalStackClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha4.MetalStackCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha3_MetalStackCluster_To_v1alpha4_MetalStackCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha3_MetalStackClusterList_To_v1alpha4_MetalStackClusterList is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackClusterList_To_v1alpha4_MetalStackClusterList(in *MetalStackClusterList, out *v1alpha4.MetalStackClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackClusterList_To_v1alpha4_MetalStackClusterList(in, out, s)
}

func autoConvert_v1alpha4_MetalStackClusterList_To_v1alpha3_MetalStackClusterList(in *v1alpha4.MetalStackClusterList, out *MetalStackClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetalStackCluster, len(*in))
		for i := range *in {
			if err := Convert_v1alpha4_MetalStackCluster_To_v1alpha3_MetalStackCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha4_MetalStackClusterList_To_v1alpha3_MetalStackClusterList is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackClusterList_To_v1alpha3_MetalStackClusterList(in *v1alpha4.MetalStackClusterList, out *MetalStackClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackClusterList_To_v1alpha3_MetalStackClusterList(in, out, s)
}

func autoConvert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec(in *MetalStackClusterSpec, out *v1alpha4.MetalStackClusterSpec, s conversion.Scope) error {
	if err := apiv1alpha3.Convert_v1alpha3_APIEndpoint_To_v1alpha4_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.ProjectID = in.ProjectID
	out.Partition = in.Partition
	out.PublicNetworkID = in.PublicNetworkID
	out.PrivateNetworkID = (*string)(unsafe.Pointer(in.PrivateNetworkID))
	if err := Convert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(&in.FirewallSpec, &out.FirewallSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec(in *MetalStackClusterSpec, out *v1alpha4.MetalStackClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackClusterSpec_To_v1alpha4_MetalStackClusterSpec(in, out, s)
}

func autoConvert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec(in *v1alpha4.MetalStackClusterSpec, out *MetalStackClusterSpec, s conversion.Scope) error {
	if err := apiv1alpha3.Convert_v1alpha4_APIEndpoint_To_v1alpha3_APIEndpoint(&in.ControlPlaneEndpoint, &out.ControlPlaneEndpoint, s); err != nil {
		return err
	}
	out.ProjectID = in.ProjectID
	out.Partition = in.Partition
	out.PublicNetworkID = in.PublicNetworkID
	out.PrivateNetworkID = (*string)(unsafe.Pointer(in.PrivateNetworkID))
	if err := Convert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(&in.FirewallSpec, &out.FirewallSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec(in *v1alpha4.MetalStackClusterSpec, out *MetalStackClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackClusterSpec_To_v1alpha3_MetalStackClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus(in *MetalStackClusterStatus, out *v1alpha4.MetalStackClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.ControlPlaneIPAllocated = in.ControlPlaneIPAllocated
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus(in *MetalStackClusterStatus, out *v1alpha4.MetalStackClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackClusterStatus_To_v1alpha4_MetalStackClusterStatus(in, out, s)
}

func autoConvert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus(in *v1alpha4.MetalStackClusterStatus, out *MetalStackClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.ControlPlaneIPAllocated = in.ControlPlaneIPAllocated
	out.FailureReason = (*errors.ClusterStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus(in *v1alpha4.MetalStackClusterStatus, out *MetalStackClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackClusterStatus_To_v1alpha3_MetalStackClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_MetalStackFirewall_To_v1alpha4_MetalStackFirewall(in *MetalStackFirewall, out *v1alpha4.MetalStackFirewall, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackFirewall_To_v1alpha4_MetalStackFirewall is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackFirewall_To_v1alpha4_MetalStackFirewall(in *MetalStackFirewall, out *v1alpha4.MetalStackFirewall, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackFirewall_To_v1alpha4_MetalStackFirewall(in, out, s)
}

func autoConvert_v1alpha4_MetalStackFirewall_To_v1alpha3_MetalStackFirewall(in *v1alpha4.MetalStackFirewall, out *MetalStackFirewall, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackFirewall_To_v1alpha3_MetalStackFirewall is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackFirewall_To_v1alpha3_MetalStackFirewall(in *v1alpha4.MetalStackFirewall, out *MetalStackFirewall, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackFirewall_To_v1alpha3_MetalStackFirewall(in, out, s)
}

func autoConvert_v1alpha3_MetalStackFirewallList_To_v1alpha4_MetalStackFirewallList(in *MetalStackFirewallList, out *v1alpha4.MetalStackFirewallList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.MetalStackFirewall)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_MetalStackFirewallList_To_v1alpha4_MetalStackFirewallList is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackFirewallList_To_v1alpha4_MetalStackFirewallList(in *MetalStackFirewallList, out *v1alpha4.MetalStackFirewallList, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackFirewallList_To_v1alpha4_MetalStackFirewallList(in, out, s)
}

func autoConvert_v1alpha4_MetalStackFirewallList_To_v1alpha3_MetalStackFirewallList(in *v1alpha4.MetalStackFirewallList, out *MetalStackFirewallList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MetalStackFirewall)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MetalStackFirewallList_To_v1alpha3_MetalStackFirewallList is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackFirewallList_To_v1alpha3_MetalStackFirewallList(in *v1alpha4.MetalStackFirewallList, out *MetalStackFirewallList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackFirewallList_To_v1alpha3_MetalStackFirewallList(in, out, s)
}

func autoConvert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(in *MetalStackFirewallSpec, out *v1alpha4.MetalStackFirewallSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.MachineType = in.MachineType
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.SSHKeys = *(*[]string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(in *MetalStackFirewallSpec, out *v1alpha4.MetalStackFirewallSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackFirewallSpec_To_v1alpha4_MetalStackFirewallSpec(in, out, s)
}

func autoConvert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(in *v1alpha4.MetalStackFirewallSpec, out *MetalStackFirewallSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.MachineType = in.MachineType
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.SSHKeys = *(*[]string)(unsafe.Pointer(&in.SSHKeys))
	return nil
}

// Convert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(in *v1alpha4.MetalStackFirewallSpec, out *MetalStackFirewallSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackFirewallSpec_To_v1alpha3_MetalStackFirewallSpec(in, out, s)
}

func autoConvert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus(in *MetalStackFirewallStatus, out *v1alpha4.MetalStackFirewallStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus(in *MetalStackFirewallStatus, out *v1alpha4.MetalStackFirewallStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackFirewallStatus_To_v1alpha4_MetalStackFirewallStatus(in, out, s)
}

func autoConvert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus(in *v1alpha4.MetalStackFirewallStatus, out *MetalStackFirewallStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus(in *v1alpha4.MetalStackFirewallStatus, out *MetalStackFirewallStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackFirewallStatus_To_v1alpha3_MetalStackFirewallStatus(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachine_To_v1alpha4_MetalStackMachine(in *MetalStackMachine, out *v1alpha4.MetalStackMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackMachine_To_v1alpha4_MetalStackMachine is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachine_To_v1alpha4_MetalStackMachine(in *MetalStackMachine, out *v1alpha4.MetalStackMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachine_To_v1alpha4_MetalStackMachine(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachine_To_v1alpha3_MetalStackMachine(in *v1alpha4.MetalStackMachine, out *MetalStackMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackMachine_To_v1alpha3_MetalStackMachine is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachine_To_v1alpha3_MetalStackMachine(in *v1alpha4.MetalStackMachine, out *MetalStackMachine, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachine_To_v1alpha3_MetalStackMachine(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineList_To_v1alpha4_MetalStackMachineList(in *MetalStackMachineList, out *v1alpha4.MetalStackMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.MetalStackMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_MetalStackMachineList_To_v1alpha4_MetalStackMachineList is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineList_To_v1alpha4_MetalStackMachineList(in *MetalStackMachineList, out *v1alpha4.MetalStackMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineList_To_v1alpha4_MetalStackMachineList(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineList_To_v1alpha3_MetalStackMachineList(in *v1alpha4.MetalStackMachineList, out *MetalStackMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MetalStackMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MetalStackMachineList_To_v1alpha3_MetalStackMachineList is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineList_To_v1alpha3_MetalStackMachineList(in *v1alpha4.MetalStackMachineList, out *MetalStackMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineList_To_v1alpha3_MetalStackMachineList(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(in *MetalStackMachineSpec, out *v1alpha4.MetalStackMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.MachineType = in.MachineType
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.SSHKeys = *(*[]string)(unsafe.Pointer(&in.SSHKeys))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(in *MetalStackMachineSpec, out *v1alpha4.MetalStackMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(in *v1alpha4.MetalStackMachineSpec, out *MetalStackMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.MachineType = in.MachineType
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.SSHKeys = *(*[]string)(unsafe.Pointer(&in.SSHKeys))
	out.Tags = *(*[]string)(unsafe.Pointer(&in.Tags))
	return nil
}

// Convert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(in *v1alpha4.MetalStackMachineSpec, out *MetalStackMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus(in *MetalStackMachineStatus, out *v1alpha4.MetalStackMachineStatus, s conversion.Scope) error {
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.InstanceStatus = (*v1alpha4.MetalStackResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.LLDP = in.LLDP
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus(in *MetalStackMachineStatus, out *v1alpha4.MetalStackMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineStatus_To_v1alpha4_MetalStackMachineStatus(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus(in *v1alpha4.MetalStackMachineStatus, out *MetalStackMachineStatus, s conversion.Scope) error {
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.ErrorReason = (*errors.MachineStatusError)(unsafe.Pointer(in.ErrorReason))
	out.ErrorMessage = (*string)(unsafe.Pointer(in.ErrorMessage))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.InstanceStatus = (*MetalStackResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.LLDP = in.LLDP
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus(in *v1alpha4.MetalStackMachineStatus, out *MetalStackMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineStatus_To_v1alpha3_MetalStackMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineTemplate_To_v1alpha4_MetalStackMachineTemplate(in *MetalStackMachineTemplate, out *v1alpha4.MetalStackMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackMachineTemplate_To_v1alpha4_MetalStackMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineTemplate_To_v1alpha4_MetalStackMachineTemplate(in *MetalStackMachineTemplate, out *v1alpha4.MetalStackMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineTemplate_To_v1alpha4_MetalStackMachineTemplate(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineTemplate_To_v1alpha3_MetalStackMachineTemplate(in *v1alpha4.MetalStackMachineTemplate, out *MetalStackMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackMachineTemplate_To_v1alpha3_MetalStackMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineTemplate_To_v1alpha3_MetalStackMachineTemplate(in *v1alpha4.MetalStackMachineTemplate, out *MetalStackMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineTemplate_To_v1alpha3_MetalStackMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineTemplateList_To_v1alpha4_MetalStackMachineTemplateList(in *MetalStackMachineTemplateList, out *v1alpha4.MetalStackMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha4.MetalStackMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_MetalStackMachineTemplateList_To_v1alpha4_MetalStackMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineTemplateList_To_v1alpha4_MetalStackMachineTemplateList(in *MetalStackMachineTemplateList, out *v1alpha4.MetalStackMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineTemplateList_To_v1alpha4_MetalStackMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineTemplateList_To_v1alpha3_MetalStackMachineTemplateList(in *v1alpha4.MetalStackMachineTemplateList, out *MetalStackMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]MetalStackMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha4_MetalStackMachineTemplateList_To_v1alpha3_MetalStackMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineTemplateList_To_v1alpha3_MetalStackMachineTemplateList(in *v1alpha4.MetalStackMachineTemplateList, out *MetalStackMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineTemplateList_To_v1alpha3_MetalStackMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource(in *MetalStackMachineTemplateResource, out *v1alpha4.MetalStackMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_MetalStackMachineSpec_To_v1alpha4_MetalStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource(in *MetalStackMachineTemplateResource, out *v1alpha4.MetalStackMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource(in *v1alpha4.MetalStackMachineTemplateResource, out *MetalStackMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha4_MetalStackMachineSpec_To_v1alpha3_MetalStackMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource(in *v1alpha4.MetalStackMachineTemplateResource, out *MetalStackMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec(in *MetalStackMachineTemplateSpec, out *v1alpha4.MetalStackMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_MetalStackMachineTemplateResource_To_v1alpha4_MetalStackMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec(in *MetalStackMachineTemplateSpec, out *v1alpha4.MetalStackMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_MetalStackMachineTemplateSpec_To_v1alpha4_MetalStackMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec(in *v1alpha4.MetalStackMachineTemplateSpec, out *MetalStackMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha4_MetalStackMachineTemplateResource_To_v1alpha3_MetalStackMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec(in *v1alpha4.MetalStackMachineTemplateSpec, out *MetalStackMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha4_MetalStackMachineTemplateSpec_To_v1alpha3_MetalStackMachineTemplateSpec(in, out, s)
}
